apiVersion: v1
kind: Service
metadata:
  name: basic-chat
  labels:
    app: basic-chat
    service: basic-chat
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: basic-chat
  type: LoadBalancer    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-chat
      version: v1
  template:
    metadata:
      labels:
        app: basic-chat
        version: v1
    spec:
      containers:
        - image: mcr.microsoft.com/mcr/hello-world:latest
          imagePullPolicy: Always
          name: basic-chat
          ports:
            - containerPort: 8080
          env:
            - name: OPEN_AI_CONNECTION_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: openai-config
                  key: openai-key
